//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Booking { get; set; }
        public string Passport { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<decimal> TicketFee { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Note { get; set; }
    }
}
